version: '3'

services:
    web3:
        build: .
        volumes:
            - ./www:/www

    web-server:
        image: nginx
        volumes:
            - ./config/nginx/site-enabled/default:/etc/nginx/conf.d/default.conf
            - ./www:/var/www
        depends_on:
            - web3
        ports:
            - 8071:8082
